version: "3.8"
services:
    plex:
        image: ghcr.io/linuxserver/plex
        container_name: plex
        environment:
            - PUID=100O
            - PGID=1000
            - VERSION=docker
            - PLEX_CLAIM=claim-Pq4AyzqjyTTApf5_88pi
        ports: 
            - 32400:32400
            - 1900:1900/udp
            - 3005:3005
            - 5352:5353/udp
            - 8324:8324
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
            - 32469:32469
        volumes:
            - ./.config/plex:/config
            - ./media/tv:/tv
            - ./media/movies:/movies
            - ./media/music:/music
            - ./media/photos:/photos
            - ./media/comics:/comics
            - ./media/media:/media
        restart: unless-stopped
    sonarr:
        image: ghcr.io/linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=100O
            - PGID=1000
            - TZ=Europe/Brussels
        volumes:
            - ./.config/sonarr:/config
            - ./media/tv:/tv
            - ./downloads:/downloads
        ports:
            - 8989:8989
        restart: unless-stopped
    radarr:
        image: ghcr.io/linuxserver/radarr
        container_name: radarr
        environment:
            - PUID=100O
            - PGID=1000
            - TZ=Europe/Brussels
        volumes:
            - ./.config/radarr:/config
            - ./media/movies:/movies
            - ./downloads:/downloads
        ports:
            - 7878:7878
        restart: unless-stopped
    deluge:
        image: ghcr.io/linuxserver/deluge
        container_name: deluge
        ports:
            - 8112:8112
        environment:
            - PUID=100O
            - PGID=1000
            - TZ=Europe/Brussels
            - DELUGE_LOGLEVEL=error 
        volumes:
            - ./.config/deluge:/config
            - ./downloads:/downloads
        restart: unless-stopped
    jackett:
        image: ghcr.io/linuxserver/jackett
        container_name: jackett
        environment:
            - PUID=100O
            - PGID=1000
            - TZ=Europe/Brussels
            - AUTO_UPDATE=true #optional
        volumes:
            - ./.config/jackett:/config
            - ./downloads:/downloads
        ports:
            - 9117:9117
        restart: unless-stopped
    traktarr:
        container_name: traktarr
        command: traktarr run
        image: eafxx/traktarr
        volumes:
            - ./.config/traktarr:/config
        environment:
            - PUID=100O
            - PGID=1000
            - TZ=Europe/Brussels
            - DELAY=2.5        
            - SORT=rating
            - NOSEARCH=yes
            - NOTIFICATIONS=yes
            - BLACKLIST=yes
            - RUNNOW=no
            - SKIPUPDATE=no
            - APP_BRANCH=master 