version: "3.8"
services:
    plex:
        image: ghcr.io/linuxserver/plex
        container_name: plex
        environment:
            - PUID=100O
            - PGID=1000
            - VERSION=docker
            - PLEX_CLAIM=claim-Pq4AyzqjyTTApf5_88pi
        ports: 
            - 32400:32400
            - 1900:1900/udp
            - 3005:3005
            - 5352:5353/udp
            - 8324:8324
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
            - 32469:32469
        volumes:
            - ./.config/plex:/config
            - ./media/tv:/tv
            - ./media/movies:/movies
            - ./media/music:/music
            - ./media/photos:/photos
            - ./media/comics:/comics
            - ./media/media:/media
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.plex.entrypoints=websecure"
            - traefik.http.routers.plex.rule=Host(`plex.${DOMAIN}`)
            - traefik.http.routers.plex.tls=true
            - traefik.http.routers.plex.service=plex
            - traefik.http.services.plex.loadbalancer.server.port=32400
            - traefik.http.routers.home-assistant.tls.certresolver=le
    sonarr:
        image: ghcr.io/linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=100O
            - PGID=1000
            - TZ=Europe/Brussels
        volumes:
            - ./.config/sonarr:/config
            - ./media/tv:/tv
            - ./downloads:/downloads
        ports:
            - 8989:8989
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.sonarr.entrypoints=websecure"
            - traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)
            - traefik.http.routers.sonarr.tls=true
            - traefik.http.routers.sonarr.service=sonarr
            - traefik.http.services.sonarr.loadbalancer.server.port=8989
            - traefik.http.routers.home-assistant.tls.certresolver=le
    radarr:
        image: ghcr.io/linuxserver/radarr
        container_name: radarr
        environment:
            - PUID=100O
            - PGID=1000
            - TZ=Europe/Brussels
        volumes:
            - ./.config/radarr:/config
            - ./media/movies:/movies
            - ./downloads:/downloads
        ports:
            - 7878:7878
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.radarr.entrypoints=websecure"
            - traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)
            - traefik.http.routers.radarr.tls=true
            - traefik.http.routers.radarr.service=radarr
            - traefik.http.services.radarr.loadbalancer.server.port=7878
            - traefik.http.routers.home-assistant.tls.certresolver=le
    deluge:
        image: ghcr.io/linuxserver/deluge
        container_name: deluge
        ports:
            - 8112:8112
        environment:
            - PUID=100O
            - PGID=1000
            - TZ=Europe/Brussels
            - DELUGE_LOGLEVEL=error 
        volumes:
            - ./.config/deluge:/config
            - ./downloads:/downloads
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.deluge.entrypoints=websecure"
            - traefik.http.routers.deluge.rule=Host(`deluge.${DOMAIN}`)
            - traefik.http.routers.deluge.tls=true
            - traefik.http.routers.deluge.service=deluge
            - traefik.http.services.deluge.loadbalancer.server.port=8112
            - traefik.http.routers.home-assistant.tls.certresolver=le
    jackett:
        image: ghcr.io/linuxserver/jackett
        container_name: jackett
        environment:
            - PUID=100O
            - PGID=1000
            - TZ=Europe/Brussels
            - AUTO_UPDATE=true #optional
        volumes:
            - ./.config/jackett:/config
            - ./downloads:/downloads
        ports:
            - 9117:9117
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.jackett.entrypoints=websecure"
            - traefik.http.routers.jackett.rule=Host(`jackett.${DOMAIN}`)
            - traefik.http.routers.jackett.tls=true
            - traefik.http.routers.jackett.service=jackett
            - traefik.http.services.jackett.loadbalancer.server.port=9117
            - traefik.http.routers.home-assistant.tls.certresolver=le
    traktarr:
        container_name: traktarr
        command: traktarr run
        image: eafxx/traktarr
        volumes:
            - ./.config/traktarr:/config
        environment:
            - PUID=100O
            - PGID=1000
            - TZ=Europe/Brussels
            - DELAY=2.5        
            - SORT=rating
            - NOSEARCH=yes
            - NOTIFICATIONS=yes
            - BLACKLIST=yes
            - RUNNOW=no
            - SKIPUPDATE=no
            - APP_BRANCH=master 
        restart: unless-stopped
    traefik:
        container_name: traefik
        image: traefik:latest
        command:
            - "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.le.acme.tlschallenge=true"
        ports:
            - 80:80
            - 8080:8080
            - 443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        network_mode: "host"
        restart: unless-stopped
    home-assistant:
        container_name: "home-assistant"
        image: homeassistant/home-assistant:latest
        devices:
            - /dev/ttyAMA0 
        healthcheck:
            test: ["CMD", "curl", "-f", "http://192.168.0.16:8123"]
            interval: 30s
            timeout: 10s
            retries: 6
        environment:
            - PUID=100O
            - PGID=1000
            - TZ=Europe/Brussels
        ports:
            - 8123:8123
        privileged: true
        volumes:
            - ./ha:/config
        cap_add:
            - NET_ADMIN
            - NET_BIND_SERVICE
            - SYS_ADMIN
        network_mode: "host"
        labels:
            - traefik.enable=true
            - traefik.http.services.home-assistant.loadbalancer.server.port=8123
            - traefik.http.routers.home-assistant.rule=Host(`ha.${DOMAIN}`)
            - traefik.http.routers.home-assistant.entrypoints=websecure
            - traefik.http.routers.home-assistant.tls=true
            - traefik.http.routers.jackett.service=homeassistant
            - traefik.http.routers.home-assistant.tls.certresolver=le
        restart: unless-stopped
    duckdns:
        container_name: duckdns
        image: linuxserver/duckdns:eb04e693-ls56
        restart: unless-stopped
    
        environment:
            - PUID=100O
            - PGID=1000
            - TZ=Europe/Brussels
            - TOKEN=${DUCKDNS_TOKEN}
            - LOG_FILE=true
        volumes:
            - /volume1/docker/duckdns:/config
networks:
    default:
        external:
            name: docker

            